### ISSUE TITLE
不具合：DBプロパティ「Rank」がRecommendに反映されない

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#11]

**Comment by otoyo** [comment]
こちらよければ詳細を書いていただいてもよろしいでしょうか？
easy-notion-blog のデモページでは反映されているように見えます。

My 1st post が Rank: 1
![スクリーンショット 2021-12-18 17 24 46](https://user-images.githubusercontent.com/1063435/146634769-dd1a418b-dc15-4618-9fe4-cad06b028665.png)

Recommended に表示されています。
![スクリーンショット 2021-12-18 17 24 55](https://user-images.githubusercontent.com/1063435/146634785-acf5c7dc-4276-4977-ae56-09b7da8ccad4.png)

**Comment by herohoro** [comment]
<img width="928" alt="スクリーンショット 2021-12-20 0 14 13" src="https://user-images.githubusercontent.com/24947347/146680221-1e289cbc-8829-4f67-8173-3f57ed83c07f.png">
👇
<img width="915" alt="スクリーンショット 2021-12-20 0 15 54" src="https://user-images.githubusercontent.com/24947347/146680292-d1c9010c-e262-4814-9118-f1d4e1943011.png">

Rankの値が降順になっている！？感じですか？？
すみません。昇順かと勘違いしていました・・・・^^;

**Comment by herohoro** [comment]
再度READMEを読み返しました。降順とありますね。
お騒がせしましたm(_ _)m^^;
<img width="967" alt="スクリーンショット 2021-12-20 0 19 41" src="https://user-images.githubusercontent.com/24947347/146680444-85c3e312-2b72-4449-9106-5abf5dc68c73.png">

**Comment by otoyo** [comment]
解決したようで良かったです。
