### ISSUE TITLE
新しい記事をnotionで書いたが反映されない

### ISSUE THREAD

**Issue by nuovotaka** [otoyo/easy-notion-blog#112]
twitterのカードも変更されているのでテストしたところ、新しい記事をNotion側で書いたがvercel側が反応しない。
Notion側ではPublishedにしているのですが。。。

**Comment by otoyo** [comment]
Notion データベースのスクリーンショットと、 [こちらの wiki](https://github.com/otoyo/easy-notion-blog/wiki/%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%A7%E5%8B%95%E3%81%8B%E3%81%AA%E3%81%8F%E3%81%AA%E3%81%A3%E3%81%9F%E3%82%89%EF%BC%88%E3%82%A8%E3%83%A9%E3%83%BC%E3%83%AD%E3%82%B0%E3%81%AE%E7%A2%BA%E8%AA%8D%E6%96%B9%E6%B3%95%EF%BC%89) を参考にエラーメッセージを確認して添付いただけますでしょうか？

**Comment by nuovotaka** [comment]
新しい記事の反映が先ほどありました。記事を書いてから１時間以上もタイムラグがあるものですか？
先程、追加した記事は数分で記事の反映がありました。
記事の反映に関するエラーは見つけられませんでした。
Twitterカードについてエラーを見つけてしまったのですが。。。別issueとします。

**Comment by otoyo** [comment]
推測ですが、記事を公開されたのは午前9時以前ではないでしょうか？

Notion, Vercel, easy-notion-blog これらは全てグローバルを前提としたサービスです。
そのため、Date にタイムゾーンと時間を指定していない場合（日付のみの場合）、世界標準時での解釈となります。
すなわち、日付のみを指定して公開した場合は世界標準時でその日付になる時間、日本時間の午前9時に公開となります。

日本時間で公開日時を指定したい場合は Notion で時間を含める設定にして時刻を指定し、タイムゾーンで日本時間（JST）を選択してください。
![スクリーンショット 2022-08-18 13 16 36](https://user-images.githubusercontent.com/1063435/185292537-1bc1de61-739f-44f2-8a38-9c536824361b.png)

**Comment by nuovotaka** [comment]
了解しました。
有難う御座いました。
早朝に記事を上げるときは時間指定をして記事を上げる。ですね。m(__)m
