### ISSUE TITLE
Twitterカードのブックマークが上手く表示されていない

### ISSUE THREAD

**Issue by nuovotaka** [otoyo/easy-notion-blog#114]
## 不具合の概要
Twitter ブックマークが画像付きで表示されない。
仕様でしょうか？

期待しているのは下記のような画像付きのブックマークです。
<img width="677" alt="スクリーンショット 2022-08-18 11 43 04" src="https://user-images.githubusercontent.com/11598404/185281341-ab87a4fe-8e3b-4826-ba16-9d1d3c850f9d.png">

## 再現方法
easy-notion-blog.nuovotaka.com
の　
https://easy-notion-blog.nuovotaka.com/blog/twitter-card

## エラーログ
Functions の内容

[GET] /_next/data/j1dAM7xsus_wvqTtJ4HOY/blog/sick-egpa-part35.json
11:24:25:15

[GET] /_next/data/j1dAM7xsus_wvqTtJ4HOY/blog/smartphonepoach2-leathercraft.json
11:24:24:68

[GET] /_next/data/j1dAM7xsus_wvqTtJ4HOY/blog/tag/blog.json
11:24:24:58

[GET] /_next/data/j1dAM7xsus_wvqTtJ4HOY/blog.json
11:24:24:58

[GET] /api/url-metadata?url=https://twitter.com/nuovotaka/status/1559998318939439108?s=21&t=rwsON9JfEczxmXI7z1F5eA
11:24:24:34
start: 1660789464533,
    socket: 1660789464533,
    lookup: 1660789464533,
    connect: 1660789464591,
    secureConnect: 1660789464607,
    upload: 1660789464608,
    response: 1660789464628,
    end: 1660789464629,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 58,
      tls: 16,
      request: 1,
      firstByte: 20,
      download: 1,
      total: 96
    }
  },
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: undefined,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: undefined,
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'got (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate, br'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 2,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'GET',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'text',
    url: URL {
      href: 'https://twitter.com/nuovotaka/status/1559998318939439108?s=21',
      origin: 'https://twitter.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'twitter.com',
      hostname: 'twitter.com',
      port: '',
      pathname: '/nuovotaka/status/1559998318939439108',
      search: '?s=21',
      searchParams: URLSearchParams { 's' => '21' },
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined,
    signal: undefined,
    enableUnixSockets: true
  }
}

## 期待する挙動
Notionでtwitterを埋め込んだモノの下にブックマークがあります。そのブックも表示させたい。
twitter ブックマークの表示(今回は画像付き)
## スクリーンショット
・Notionのスクショ
<img width="746" alt="スクリーンショット 2022-08-18 11 16 02" src="https://user-images.githubusercontent.com/11598404/185281144-e00fc1fe-37a3-4e02-b167-25f29f4dab28.png">

<img width="699" alt="スクリーンショット 2022-08-18 11 16 29" src="https://user-images.githubusercontent.com/11598404/185281172-d4236ac8-00e5-4c79-9068-7ed353b10914.png">

<img width="698" alt="スクリーンショット 2022-08-18 11 16 50" src="https://user-images.githubusercontent.com/11598404/185281095-03d560cc-1173-4c31-8424-7cb820ea6af5.png">

・エラーが発生している画面のスクリーンショットを添付します。
<img width="1233" alt="スクリーンショット 2022-08-18 11 13 41" src="https://user-images.githubusercontent.com/11598404/185280244-9d26feca-9008-4e20-bad9-c32dac4f9839.png">

## リポジトリとブランチ名
もし Fork した easy-notion-blog でエラーが発生している場合には、あなたのリポジトリの URL とブランチ名を記載します。
https://github.com/nuovotaka/easy-notion-blog
main ブランチ　#111 
## デスクトップ環境
 - OS: [MacOS]　big sur 
 - ブラウザ: [Brave]
 - ブラウザのバージョン: [1.42.97 Chromium: 104.0.5112.102（Official Build） （x86_64）](https://brave.com/latest/)

## 追加情報
他に伝えておくべき追加情報があれば記述します。

**Comment by otoyo** [comment]
Twitter を表示したい場合にはブックマークではなく Embed Tweet を選択していただければ下記のようなカードが表示されます。

![スクリーンショット 2022-08-18 13 04 57](https://user-images.githubusercontent.com/1063435/185291223-eb1fe0a4-9c1a-4308-b061-eeedfd2342fe.png)

Twitter の URL を Notion に貼り付けた際にメニューが出るので Embed Tweet を選択してください。

![スクリーンショット 2022-08-18 13 03 13](https://user-images.githubusercontent.com/1063435/185291153-625bf901-85a7-4901-813c-39eaaac928c6.png)

ツイートのURLをブックマークした際に情報が表示されないのは、ツイートURLには一般的なサイト情報を表すメタ情報がないためとなります。
対応は可能ですが、他のユーザーからも需要があれば対応したいと思います。
基本的には easy-notion-blog は自分で必要なものは自分でカスタマイズしていただくというスタンスです。

**Comment by nuovotaka** [comment]
了解しました。
TwitterはEmbed Tweetを選択するようにします。
有難う御座いました。
