### ISSUE TITLE
初期設定時に複製するNotionDBのSupport blocksの記事内の不具合

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#115]
## 不具合の概要
NotionDBのテンプレート内のbookmarkブロックが異なるブロックになっている

## 再現方法

1. NotionDBを複製して取り込む
2. 初期設定を済ませVercelでDeploy
3. サンプル記事「Support blocks」を開く
4. Link Preview & Bookmarkの部分までスクロールすると表示されていない

## 修正前のNotion
<img width="590" alt="スクリーンショット 2022-08-24 20 39 59" src="https://user-images.githubusercontent.com/24947347/186460371-22f84955-9fd4-4a93-a80e-29300884626b.png">

## 期待する挙動
bookmarkブロックを表示するために修正するとブログでも表示されました
<img width="598" alt="スクリーンショット 2022-08-24 20 41 28" src="https://user-images.githubusercontent.com/24947347/186460642-5819a274-440e-4949-bac6-96dba211476f.png">

## デスクトップ環境
 - OS: MacOS
 - ブラウザ: Chrome
 - ブラウザのバージョン: ？？

## 追加情報
NotionDBを複製する際、アルパカ先生のいつものアイコンではないアイコンが表示されていましたが大丈夫でしょうか？？？
(アルパカ先生はアルパカでいてほしい願望ありです....(´・ω・｀))

**Comment by otoyo** [comment]
テンプレートのブックマークブロックを修正しました。報告ありがとうございました。
ついでにアイコンも GitHub にあわせておきました。

**Comment by herohoro** [comment]
ありがとうございますー(*^^*)
アイコン。。わがままを聞いてくださり感謝です( ﾟдﾟ)
