### ISSUE TITLE
テキストに日付またはリマインダーを挿入するとエラーが発生する

### ISSUE THREAD

**Issue by nuovotaka** [otoyo/easy-notion-blog#134]
## 不具合の概要
日付またはリマインダーを挿入すると「return null」がないとエラーが出る

## 再現方法
パブリッシュでないテストページにて行った。
1. テストページを作成する（slug,公開日付等の設定をする）
2. 内容に「日付またはリマインダーを挿入する」
3. yarn dev
<img width="615" alt="スクリーンショット 2022-11-06 13 13 04" src="https://user-images.githubusercontent.com/11598404/200154056-17fb663c-84fb-4903-b9c3-af7651e31356.png">

<img width="608" alt="スクリーンショット 2022-11-06 13 13 23" src="https://user-images.githubusercontent.com/11598404/200154063-672a19e8-e591-4b25-8f57-12425a910b13.png">

## エラーログ
<img width="758" alt="スクリーンショット 2022-11-06 13 13 59" src="https://user-images.githubusercontent.com/11598404/200154068-d77d7d3b-4702-4d1a-b0be-8ec6d6005746.png">

## 期待する挙動
mentionに対応していないので何も表示しない

## スクリーンショット
エラーが発生している画面のスクリーンショットを添付します。
<img width="960" alt="スクリーンショット 2022-11-06 13 14 56" src="https://user-images.githubusercontent.com/11598404/200154076-17193cec-1305-45e4-b8bd-78d30615e028.png">

## リポジトリ
https://github.com/nuovotaka/notion-blog

## デスクトップ環境
 - OS: [MacOS]
 - ブラウザ: [Brave]
 - ブラウザのバージョン: [ 1.45.118 Chromium: 107.0.5304.91（Official Build） （x86_64）]

## 追加情報
なし

**Comment by otoyo** [comment]
ご報告ありがとうございます。 https://github.com/otoyo/easy-notion-blog/pull/135 で修正しましたのでご確認ください。
