### ISSUE TITLE
不具合：SNSボタン押下後に発行されるリンクに「/」が１つ不足する

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#16]
vercelでの登録を修正後無事にボタンは設置され、
ボタンを押してみると・・・・

<img width="611" alt="スクリーンショット 2021-12-19 22 13 01" src="https://user-images.githubusercontent.com/24947347/146676092-0d7c03ad-c6f0-469c-a0db-b58c01238b68.png">

「/」が１つ不足した状態で発行されてしまいますm(_ _)m

https://easy-notion-blog-02.vercel.app/blog/v0111_sns_setting

**Comment by otoyo** [comment]
ご報告ありがとうございます。こちら不具合ですので修正しますね。
~#17 もおそらく同じ原因だと思います。~ 別の問題でした。

**Comment by herohoro** [comment]
ありがとうございますーーーーー。(*´∀｀*)

**Comment by otoyo** [comment]
https://github.com/otoyo/easy-notion-blog/pull/20 で修正しました。

**Comment by herohoro** [comment]
さっそくの対応ありがとうございます!!!!!
無事に「/」が不足せず発行させることができました＼(^o^)／
<img width="588" alt="スクリーンショット 2021-12-20 10 27 13" src="https://user-images.githubusercontent.com/24947347/146699234-f25c5d67-0ed9-4de7-8637-028493c8d532.png">
