### ISSUE TITLE
不具合：記事リンクを直接SNSに貼り付けた際、デフォルト画像が表示されず

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#17]
<img width="1028" alt="スクリーンショット 2021-12-19 22 25 20" src="https://user-images.githubusercontent.com/24947347/146676475-b848b743-e1da-4f98-b98a-5d67a67bc4ce.png">
👇
<img width="592" alt="スクリーンショット 2021-12-19 22 10 10" src="https://user-images.githubusercontent.com/24947347/146676488-db6f5c7b-d906-4c77-b7b0-124fc463507a.png">

**Comment by otoyo** [comment]
easy-notion-blog ではデフォルトの og:image は対応していなくて（ちょうど良い画像が
用意できないため）、私個人の [notion-blog](https://github.com/otoyo/notion-blog) の方では対応しているので、`defaultOgImageUrl` のあたりを参考にした後に差分が上書きされてしまったのだと思います。

`header.tsx` の下記の箇所に修正を入れていただくとデフォルト画像が表示されるようになると思います。
```diff
-         {ogImageUrl ? <meta property="og:image" content={ogImageUrl} /> : ''}
-         {ogImageUrl ? (
-           <meta property="twitter:image" content={ogImageUrl} />
-         ) : (
-           ''
-         )}
+         <meta property="og:image" content={ogImageUrl ? ogImageUrl : defaultOgImageUrl} />
+         <meta property="twitter:image" content={ogImageUrl ? ogImageUrl : defaultOgImageUrl} />
```
https://github.com/herohoro/easy-notion-blog-02/blob/7eddd19a8a4a1c692a4fd06deae8d7fd75e27d50/src/components/header.tsx#L44-L49

**Comment by herohoro** [comment]
コードを修正後、確認してみましたが、変わらず非表示でした。
少し待てば改善されるかとも思うので急がず待つことにします。

修正後に１点気になる変化がありまして、
SNSボタン押下時も試してみると新規タブではなく謎のwindowが開くようになりました(´・ω・`)
<img width="943" alt="スクリーンショット 2021-12-20 11 21 05" src="https://user-images.githubusercontent.com/24947347/146702682-5ee433f6-0e40-48b8-a3d0-e43dd7b161e6.png">

**Comment by herohoro** [comment]
少し待ってから再度確認したところ無事に表示されました＼(^o^)／
<img width="837" alt="スクリーンショット 2021-12-20 12 43 15" src="https://user-images.githubusercontent.com/24947347/146708878-79de16b6-bbe1-477e-954b-e3bc6e3c4448.png">

**Comment by otoyo** [comment]
修正のご確認ありがとうございました。
og:image がすぐに反映されない時は Twitter Card Validator でプレビューしてみてください。
別 Window で開くのはおそらくブラウザによるものと思います（私のブラウザでは最初から別ウィンドウで開いていました）。

**Comment by herohoro** [comment]
Twitter Card Validator今後活用させていただきます⭐
勉強になりました。ありがとうございます(*´ω｀*)
