### ISSUE TITLE
不具合：ブログ記事リンクを他の記事にbookmarkとして添付すると画像は非表示になる

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#18]
<img width="836" alt="スクリーンショット 2021-12-20 1 11 17" src="https://user-images.githubusercontent.com/24947347/146682166-821ca9c1-e601-4c9e-8d7a-70230e46c0db.png">
👇
<img width="687" alt="スクリーンショット 2021-12-20 1 12 30" src="https://user-images.githubusercontent.com/24947347/146682175-b4e4ecf7-5d25-491d-88de-39d5bea9569a.png">

OGImageを登録した記事、登録していない記事、両方で試しましたが共に非表示でした。

**Comment by otoyo** [comment]
og:image が場合によって非表示になる（取得できない）のは Next.js と Notion API の仕様上どうしようもない部分だったりします。
いちおう og:image が設定されている記事のURLを下記の Twitter Card Validator に入力して2回程度 Preview して確認できれば Twitter 上でも正しく表示されるようにはなります。
https://cards-dev.twitter.com/validator

**Comment by herohoro** [comment]
!!!!Twitter Card Validatorで確認したところ問題なく表示されていました!!!!
仕様の問題が絡んでいたんですね😅勉強になります!!

**Comment by herohoro** [comment]
無事確認できました＼(^o^)／

▼ notion上
<img width="884" alt="スクリーンショット 2021-12-20 12 28 51" src="https://user-images.githubusercontent.com/24947347/146707671-607ae38a-0852-4ad0-8df6-c9c346a34d47.png">

▼ ブログ上
<img width="774" alt="スクリーンショット 2021-12-20 12 44 14" src="https://user-images.githubusercontent.com/24947347/146708782-62e3f466-a11e-4b1b-8da8-e98724c2281f.png">

**Comment by otoyo** [comment]
ご確認ありがとうございました。
Notion API から取得できる画像URLには期限があって、その期限を過ぎてしまったために画像が切れていたということになります。
