### ISSUE TITLE
不具合：yarn dev から開発環境リンクへ飛ぶとエラー

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#19]
12/18に[プレビューの解説記事](https://easy-notion-blog-02.vercel.app/blog/support_preview_setting)を書いていたときは記事一覧まで遷移できていましたが、

今日になってHomeからエラーになってしまいます。
<img width="1181" alt="スクリーンショット 2021-12-20 1 26 43" src="https://user-images.githubusercontent.com/24947347/146682622-87e76753-8753-4d71-b38f-2e1b8a635a2b.png">

振り返ってみると・・・
今日以下の２つを同期してます。(おそらくその後かと・・・)
<img width="841" alt="スクリーンショット 2021-12-20 1 33 13" src="https://user-images.githubusercontent.com/24947347/146682856-1239d6e5-419c-4cbb-bdd7-0ff1e74b763b.png">

同期後エラーになっているコードが１つありまして、それも気になるので添付します。
<img width="868" alt="スクリーンショット 2021-12-20 1 31 06" src="https://user-images.githubusercontent.com/24947347/146682925-e47d8d78-ed31-4d5e-95ea-16769364c639.png">

**Comment by herohoro** [comment]
また、12/18の時点では記事一覧ページまでは遷移できるものの、記事ページへ遷移しようとするとエラーとなっていました。

解説記事では記事一覧ページまでで止めて公開しています。
https://easy-notion-blog-02.vercel.app/blog/support_preview_setting

**Comment by otoyo** [comment]
パッケージを追加したので、ローカルでもパッケージのインストールが必要になります（赤の下線部分）。

`.next` フォルダをフォルダごと削除し、
```
$ yarn install
$ yarn dev
```
すると直るかと思います。

**Comment by herohoro** [comment]
無事に直りました＼(^o^)／

`.next`フォルダを丸ごと削除するのに
ドキドキしましたが、
無事に動いてくれたのでホッとしてます(*´ω｀*)
<img width="1100" alt="スクリーンショット 2021-12-20 11 52 09" src="https://user-images.githubusercontent.com/24947347/146705361-270832f6-5b69-422e-92a9-44d9c29f62fd.png">

▼プレビュー記事も修正済です
https://easy-notion-blog-02.vercel.app/blog/support_preview_setting

**Comment by otoyo** [comment]
解決して良かったです。修正のご確認ありがとうございました。
