### ISSUE TITLE
「easy-notion-blog」について

### ISSUE THREAD

**Issue by t0ns0ku426** [otoyo/easy-notion-blog#24]
Issuesでの投稿失礼致します。

最近になってから、「easy-notion-blog」を利用させていただいております。
そしてその中で色々と分からないことがありまして、「クイックスタート」内のものでいくつかご質問をさせていただきます。

【**質問1**】8番目の「**ターミナルアプリ**」というのはWindowsでいうと「**Git Bash**」でよろしいでしょうか？

【**質問2**】9番目の「**初期化スクリプトを実行します**」という所で...

**【DATABASE_ID=<YOUR_DATABASE_ID> NOTION_API_SECRET=<YOUR_NOTION_API_SECRET> ./scripts/init-database.sh】**

を「Git Bash」に入力したのですが、以下のようになってしまうのですがどのようにすればよいでしょうか？

**【$ DATABASE_ID=<YOUR_DATABASE_ID> NOTION_API_SECRET=<YOUR_NOTION_API_SECRET> ./scripts/init-database.sh
bash: YOUR_DATABASE_ID: No such file or directory】**

自身がプログラミング及び、Githubの初心者故に本当の初期の初期段階(まず「初期化スクリプト」という言葉自体等々)で分からないという状態で大変申し訳ないのですが、是非ともご回答の方を宜しくお願い致します。

**Comment by otoyo** [comment]
> 8番目の「ターミナルアプリ」というのはWindowsでいうと「Git Bash」でよろしいでしょうか？

Windows マシンを持っていないので動作確認はできませんが、ざっと調べたところ Git Bash で問題ないかと思います。

> 9番目の「初期化スクリプトを実行します」という所で...

`<YOUR_DATABASE_ID>` は手順5でメモしたご自身の `DATABASE_ID` に置き換えてください。
`<YOUR_NOTION_API_SECRET>` は手順6でメモしたご自身の `NOTION_API_SECRET` に置き換えてください。

もしそれでもエラーになるようでしたらエラーメッセージをコピーしてこちらの Issue にコメントとして記載をお願いします。

**Comment by t0ns0ku426** [comment]
> Windows マシンを持っていないので動作確認はできませんが、ざっと調べたところ Git Bash で問題ないかと思います。

確認ありがとうございます。今後も問題が無ければ「Git Bash」でやろうと思います。

> <YOUR_DATABASE_ID> は手順5でメモしたご自身の DATABASE_ID に置き換えてください。
<YOUR_NOTION_API_SECRET> は手順6でメモしたご自身の NOTION_API_SECRET に置き換えてください。

自身のDATABASE_ID と NOTION_API_SECRET に置き換えたのですが、以下のエラーが発生してしまいました。

**bash: syntax error near unexpected token `<'**

宜しくお願いします。

**Comment by otoyo** [comment]
エラーメッセージを見るに `DATABASE_ID` と `NOTION_API_SECRET` に `<>` が含まれていそうです。
`DATABASE_ID` が `aaa` とすると、
```
DATABASE_ID='aaa' NOTION_API_SECRET='bbb' ./scripts/init-database.sh
```
のようにクォートを使って実行してみてください。

**Comment by t0ns0ku426** [comment]
ありがとうございます。

`DATABASE_ID='aaa' NOTION_API_SECRET='bbb' ./scripts/init-database.sh`

をご使用させてもらいつつ、自身の`DATABASE_ID`と`NOTION_API_SECRET`とともに入力してみたのですが、
前回とは異なる以下のエラーが発生してしまいました。

`bash: ./scripts/init-database.sh: No such file or directory`

宜しくお願いします。

**Comment by otoyo** [comment]
エラーログに原因が書かれていますね。エラーログでお調べになりましたか？
それは easy-notion-blog の問題ではありませんので、ご自身で調べながら頑張ってみてください。

easy-notion-blog はプログラムを書くにあたっての試行錯誤すらも楽しんでもらう目的で作っています。
下記に先人が残してくれたブログもあるので参考にしてみてください。
https://easy-notion-blog-02.vercel.app/blog/easy-notion-blog-firstdeploy

もしそういうのを楽しめない（手っ取り早く Notiion でブログをやりたい）ということでしたら Super というサービスがあるのでご検討ください。
https://super.so/

**Comment by t0ns0ku426** [comment]
＜＜【2022/02/06編集】Issueが閉じている中での再投稿及び再編集を失礼致します。＞＞

上記にありました

`bash: ./scripts/init-database.sh: No such file or directory`

のエラーは解決いたしましたことを、こちらでご報告させていただきます。

解決方法としてはまず、ローカルリポジトリにクローンしました「easy-notion-blog」内にあります
`init-database.sh`というファイルの有無を確認し、

![スクリーンショット (134)](https://user-images.githubusercontent.com/98651974/152671531-211d3ff9-7fad-46ee-97b1-359354550a0e.png)
そのファイルとファイルのある場所を再確認して改めて「**Git Bash**」にて

`DATABASE_ID='aaa' NOTION_API_SECRET='bbb' ./scripts/init-database.sh`から

`DATABASE_ID='aaa' NOTION_API_SECRET='bbb' /c/Users/[ユーザー名]/easy-notion-blog/scripts/init-database.sh`に

することでひとつ作業が進むことが出来ました。しかし、その際にもエラーが発生し、
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   529  100   105  100   424     45    183  0:00:02  0:00:02 --:--:--   228{"object":"error","status":400,"code":"validation_error","message":"Name is not a valid property schema"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1209  100   329  100   880    481   1289 --:--:-- --:--:-- --:--:--  1772{"object":"error","status":400,"code":"validation_error","message":"Page is not a property that exists. Excerpt is not a property that exists. Slug is not a property that exists. Date is not a property that exists. Tags is not a property that exists. Published is not a property that exists. Rank is not a property that exists."}
```
このエラーが[こちら](https://developers.notion.com/reference/errors#request-limits)にありますNotionのエラーコード一覧で確認すると、`validation_error`というのは分かったのですが、そこからまた行き詰まりまして、ひとつ助言を頂けましたら幸いです。

**Comment by herohoro** [comment]
先程「先人が残してくれた〜」でご紹介いただいた記事の主です。
私もいろいろはじめてで悪戦苦闘しました。
githubもたいへんですよね。何が何やらで。。。。

はじめよくつまずいた部分の１つに、「使いたいファイルのあるフォルダへ移動してからコマンドを入力できているか？」といった部分でした。
普段あまりターミナル(windowsですとコマンドプロンプトのような機能です)を使う経験がないと、
クリックして開いたフォルダで作業できる状態が普通だと思いこんでしまいますが(私は以前そうでした)、
ターミナルですとその都度移動します。
現在地を説明文と合わせて進める必要があります。
今回の場合ですとクイックスタート8で記述のある『easy-notion-blogフォルダに移動する』の部分です。
<img width="967" alt="スクリーンショット 2022-02-07 12 32 41" src="https://user-images.githubusercontent.com/24947347/152720469-f6533b38-81f5-43fa-b8e1-c6f0408acc96.png">

クイックスタート9は移動後の位置からのパスで説明されています。

また、「説明中にある記号もどこまでを同じにしてどこからを差し替えるのか・・・・」といった部分でも格闘しました。
何度かいろんなリポジトリを導入して分かってきたことでしたが、値として差し替える場合だいたいが「シングルクォーテーション(')で括る」ものなんだなということも分かりました。

github関連の基礎的な感覚を付けるのに頼りになった書籍をご紹介させていただくと・・・
[わかばちゃんと学ぶ Git使い方入門](https://www.amazon.co.jp/%E6%94%B9%E8%A8%822%E7%89%88-%E3%82%8F%E3%81%8B%E3%81%B0%E3%81%A1%E3%82%83%E3%82%93%E3%81%A8%E5%AD%A6%E3%81%B6-Git%E4%BD%BF%E3%81%84%E6%96%B9%E5%85%A5%E9%96%80%E3%80%88GitHub%E3%80%81SourceTree%E3%80%81%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E6%93%8D%E4%BD%9C%E5%AF%BE%E5%BF%9C%E3%80%89-%E6%B9%8A%E5%B7%9D-%E3%81%82%E3%81%84/dp/4863543433)


私の記事に初期化スクリプトの追記をしてみました。
<img width="795" alt="スクリーンショット 2022-02-06 21 09 06" src="https://user-images.githubusercontent.com/24947347/152680064-b94ebe8d-b552-4aeb-94b0-63293b3d82b1.png">
https://easy-notion-blog-02.vercel.app/blog/easy-notion-blog-firstdeploy

クイックスタートの説明に読み飛ばしている箇所はないかといったことも再度確認しながら、
vercelでの公開を果たしてください＼(^o^)／

私は公開した時に花びらがパラパラ〜となったときに泣きそうになったほどエラーと格闘したのを覚えています(´；ω；｀)ﾌﾞﾜｯ
一緒に楽しんでいきましょ＼(^o^)／＼(^o^)／

**Comment by otoyo** [comment]
Notionデータベースの見出しが日本語で作成されているかもしれません。
もしデータベースの見出しが「名前」「タグ」になっていたらそれらを半角で `Name` と `Tags` に変更後、初期化スクリプトを実行前してみてください。

**Comment by otoyo** [comment]
上記再現したので README を修正済みです。
解決しましたら教えていただけますと幸いです。

**Comment by t0ns0ku426** [comment]
@herohoroさん　@otoyoさん

どうも「**t0ns0ku426**」です。こちらのIssueでのお返事を有り難うございます。

先程、確認を致しましたところ、自身の**Notion**での言語設定が「**日本語**」になっておりましたので

![スクリーンショット (143)](https://user-images.githubusercontent.com/98651974/152797964-639de474-6db1-453e-9146-00befd4df12f.png)

「**Table - Inline**」も以下のような状態になっておりました。
![スクリーンショット (144)](https://user-images.githubusercontent.com/98651974/152798778-173a9062-7bfe-45e6-8a29-91be6547a5f9.png)なので、言語設定を「**English**」に直し

![スクリーンショット (142)](https://user-images.githubusercontent.com/98651974/152799070-f994a880-40b0-497a-a061-293753e2017d.png)

`Name`と`Tags`をそれぞれの場所に入力致しました。（※自身の場合ですと「日本語」から「English」に切り替えたのが影響したのか、タイトルである`Untitle`は変わったのですが、中身である`Name`と`Tags`が日本語のままでした...。）
![スクリーンショット (141)](https://user-images.githubusercontent.com/98651974/152799766-6c33c872-0c6c-4913-9ac4-d1ecb3fa7e44.png)そして再び「**Git Bash**」にて「**初期化スクリプト**」実行し、なんとか無事に成功することができました。
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1429  100  1005  100   424    540    228  0:00:01  0:00:01 --:--:--   769{"object":"database","id":"[自身のデータベースID]","cover":null,"icon":null,"created_time":"2022-02-02T06:36:00.000Z","last_edited_time":"2022-02-07T14:01:00.000Z","title":[],"properties":{"Published":{"id":"Lgn%7B","name":"Published","type":"checkbox","checkbox":{}},"OGImage":{"id":"N%5BMC","name":"OGImage","type":"files","files":{}},"Date":{"id":"RoDY","name":"Date","type":"date","date":{}},"Tags":{"id":"hg%5Cy","name":"Tags","type":"multi_select","multi_select":{"options":[{"id":"5f6b0271-8cf9-4151-84a9-45b4c82dcd0b","name":"Diary","color":"pink"}]}},"Excerpt":{"id":"spE%5D","name":"Excerpt","type":"rich_text","rich_text":{}},"Rank":{"id":"tivh","name":"Rank","type":"number","number":{"format":"number"}},"Slug":{"id":"u%5DOs","name":"Slug","type":"rich_text","rich_text":{}},"Page":{"id":"title","name":"Page","type":"title","title":{}}},"parent":{"type":"page_id","page_id":"c996296d-d09f-434e-9448-621a8e304161"},"url":"https://www.notion.so/[自身のデータベースID]"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2466    0  1586  100   880   1087    603  0:00:01  0:00:01 --:--:--  1692{"object":"page","id":"e0051719-9d09-4025-872c-048ff95d12c6","created_time":"2022-02-07T14:01:00.000Z","last_edited_time":"2022-02-07T14:01:00.000Z","cover":null,"icon":null,"parent":{"type":"database_id","database_id":"[自身のデータベースID]"},"archived":false,"properties":{"Published":{"id":"Lgn%7B","type":"checkbox","checkbox":true},"OGImage":{"id":"N%5BMC","type":"files","files":[]},"Date":{"id":"RoDY","type":"date","date":{"start":"2021-11-03","end":null,"time_zone":null}},"Tags":{"id":"hg%5Cy","type":"multi_select","multi_select":[{"id":"5f6b0271-8cf9-4151-84a9-45b4c82dcd0b","name":"Diary","color":"pink"}]},"Excerpt":{"id":"spE%5D","type":"rich_text","rich_text":[{"type":"text","text":{"content":"This is an excerpt.","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"This is an excerpt.","href":null}]},"Rank":{"id":"tivh","type":"number","number":1},"Slug":{"id":"u%5DOs","type":"rich_text","rich_text":[{"type":"text","text":{"content":"my-first-post","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"my-first-post","href":null}]},"Page":{"id":"title","type":"title","title":[{"type":"text","text":{"content":"My 1st post","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"My 1st post","href":null}]}},"url":"https://www.notion.so/My-1st-post-e00517199d094025872c048ff95d12c6"}
```
![スクリーンショット (140)](https://user-images.githubusercontent.com/98651974/152801123-2955c3cc-49c7-4ff7-88b1-4f2aa623b48d.png)
herohoroさん・otoyoさん 

今回の問題解決へのお二方の丁寧な対応と、的確なアドバイスを本当に有り難うございました。

**Comment by otoyo** [comment]
@t0ns0ku426 さん
ご報告ありがとうございます。解決したようでよかったです。

Notion の日本語インターフェイスはまだリリースされて間もないこともあり盲点でした。ご報告感謝します。
ちなみにデータベースの列名さえ英語表記になっていたら、Notion の言語設定は日本語にしていただいても大丈夫です。

それでは Notion ブログをお楽しみください。
