### ISSUE TITLE
開発画面上の不具合：slugページを開くとエラー

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#31]
vercelへdeployはできるものの、
yarn devではエラー画面になります。

<img width="775" alt="スクリーンショット 2022-02-10 13 52 18" src="https://user-images.githubusercontent.com/24947347/153339676-e3b13fc3-348c-42fd-a19e-237522a2f740.png">

▼ターミナル
<img width="491" alt="スクリーンショット 2022-02-10 13 55 33" src="https://user-images.githubusercontent.com/24947347/153339905-19498612-5076-46cd-bdae-42ac3753a9b4.png">

**Comment by otoyo** [comment]
ご報告ありがとうございます。
こちらは不具合でしたので https://github.com/otoyo/easy-notion-blog/pull/34 で修正しました。

**Comment by herohoro** [comment]
ありがとうごさいますm(_ _)mm(_ _)m
