### ISSUE TITLE
不具合：本文連続改行の反映

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#32]
改行をして次までの行間を調整しようとすると反映されず、
空ブロックを埋め込むことができません。。。

▼Notion上で３行連続改行
<img width="805" alt="スクリーンショット 2022-02-10 14 03 25" src="https://user-images.githubusercontent.com/24947347/153340759-9d7858cb-f781-4a73-89b4-db8ea73786c8.png">

▼ブログ上では反映されず
<img width="731" alt="スクリーンショット 2022-02-10 13 59 17" src="https://user-images.githubusercontent.com/24947347/153340378-59053ca8-c88d-48fa-970e-76c100c3af2e.png">
[該当箇所を見出し変更したのでこのリンクで飛べます](https://easy-notion-blog-02.vercel.app/blog/support_check#%E2%96%BC%20%E7%A9%BA%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF(%EF%BC%93%E8%A1%8C%E9%80%A3%E7%B6%9A))

**Comment by otoyo** [comment]
![スクリーンショット 2022-02-10 18 22 06](https://user-images.githubusercontent.com/1063435/153376908-8df9ad37-934e-49fd-920f-64fe80d01606.png)
HTMLでは空の `<p>` タグは出力されているのでCSSの問題ですね。
該当の p 要素に `min-height` がないのが原因です。

easy-notion-blog では下記のように `min-height` を設定しています。
https://github.com/otoyo/easy-notion-blog/blob/5f4ba7dad56f3669cbbb68a158687407f441114f/src/styles/blog.module.css#L83-L88

ちなみにこの現象はマージンの相殺と呼ばれます。今回は下記リンクの「空ブロック」に該当します。
ぜひ参照してみてください。
https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

**Comment by herohoro** [comment]
ドキュメントリンクまでありがとうございます！まさにその「空ブロック」に

>あるブロックの [margin-top](https://developer.mozilla.org/ja/docs/Web/CSS/margin-top) を [margin-bottom](https://developer.mozilla.org/ja/docs/Web/CSS/margin-bottom) と隔てる境界、パディング、インラインコンテンツ、 [height](https://developer.mozilla.org/ja/docs/Web/CSS/height), [min-height](https://developer.mozilla.org/ja/docs/Web/CSS/min-height) のいずれもがない場合、上端と下端のマージンは相殺されます。

と記載があり、`min-height`でマージン相殺を防いでおられたということだったんですね。
行の高さの設定かなにかかと思いcherry-pickの際不採用しておりました。。。。。

早速コードを追加したところ無事に連続空行を反映させることができましたm(_ _)m
