### ISSUE TITLE
質問：デフォルトogimageの設定

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#33]
document-headコンポネントのurlOgImageの値に画像リンクを追記後
null部分を以下のように変更しました。

<img width="829" alt="スクリーンショット 2022-02-10 14 17 49" src="https://user-images.githubusercontent.com/24947347/153342399-4da9888c-c3aa-4b53-acc5-7595ae997268.png">

https://github.com/herohoro/easy-notion-blog-02/commit/8fa6d3ecd5cad40c33bcd954919d44d7e6587b3d

deploy直後にツイッターで確認してみましたが反映されずの状態で投稿させていだたいております。
少し待てば反映されますか？
それとも変更の仕方が間違えている部分がありますでしょうか？

**Comment by otoyo** [comment]
以前 https://github.com/otoyo/easy-notion-blog/issues/17#issuecomment-997580626 で一度お伝えしたと思いますが [Twitter Card Validator](https://cards-dev.twitter.com/validator) で該当ページのURLを入力してプレビューしたでしょうか？
Twitter は og-image をキャッシュするので Card Validator でキャッシュを更新してあげる必要があります。

貼っていただいたコミットのコードは問題なさそうです。

**Comment by herohoro** [comment]
早速のご対応ありがとうございます。
そして過去のIssueリンクまで添付してくださり感謝感謝です。

#17 を改めて見返して気づきました。
今回`null`と記載があった部分。前回は'空'でしたが・・・
[「urlOgImageがあったら使ってね」っていうメッセージ](https://github.com/otoyo/easy-notion-blog/issues/17#issuecomment-997491000)が込められていたんですね。。

Card Validatorはキャッシュを更新してくれる機能がありましたか・・・。
開発画面のようなお試しページだと思い込んでおり、
「テストしないで本番で確認すればいいかな〜」と軽率な行動を取ってしまいました(^_^;)

新規投稿時に入れたサムネを後から変更したい場合にも
このキャッシュ更新機能のCard Validatorを使えば過去ツイートも反映される・・・といった便利ツールだったんですね(； ･`д･´)

デフォルト画像の設定で２度もお騒がせしてしまい申し訳ありませんでしたm(_ _)mm(_ _)m

**Comment by otoyo** [comment]
Next.js は React というフレームワークを拡張して使われていますので、React について学ぶとコードをより深く理解できると思います。
https://ja.reactjs.org/docs/conditional-rendering.html
