### ISSUE TITLE
Vercel上でのエラーログについて

### ISSUE THREAD

**Issue by t0ns0ku426** [otoyo/easy-notion-blog#39]
「**Vercel**」でデプロイする際に、以下の複数のエラーが発生してしまいました。

(以下のスクショ画像の掲載を失礼致します。)

![スクリーンショット (149)](https://user-images.githubusercontent.com/98651974/153992706-ffab5f68-0fd3-4d9b-9d0a-75bf139ba336.png)

![スクリーンショット (151)](https://user-images.githubusercontent.com/98651974/153992723-5b999842-c167-4306-bd1f-2011b1c9b013.png)
`Environment Variables`での`NOTION_API_SECRET`と`DATABASE_ID`の入力間違いがないか等も見直してみたのですが、

最終的には`Error: Command "yarn run build" exited with 1`という表示に何度もなってしまいました。

この件に関しましての、アドバイス等々を頂けましたら幸いです。

**Comment by herohoro** [comment]
!!　ちょうど私も昨日同じエラーと格闘してクリアしたところでした(なんという偶然！！)

Next.jsのバージョンアップさせるためのリリース
https://github.com/otoyo/easy-notion-blog/releases/tag/v0.5.0
により、同期後yarnがエラーになったんですよね？？

私のリポジトリにその時行ったコマンドのメモと参照記事リンクも記載しています。
https://github.com/herohoro/easy-notion-blog-02/commit/fa742694fdf364a8f1c58c8e8e50e441868264ce#commitcomment-66819784

reactとnext.jsを最新版にしたのちに再度Vercelの機嫌を伺ってみてください！

**Comment by otoyo** [comment]
`NOTION_API_SECRET is missing from env` とあるように `NOTION_API_SECRET` が設定されていないことが原因です（入力間違いではなく）。
Vercel に行き該当の easy-notion-blog プロジェクトの Settings > Environment Variables で `NOTION_API_SECRET` が Production および Preview 環境に対して設定されていることをご確認ください。
![スクリーンショット 2022-02-18 8 21 34](https://user-images.githubusercontent.com/1063435/154588235-9e135009-e164-4453-a173-bef9832bd6cf.png)

**Comment by t0ns0ku426** [comment]
@herohoroさん　@otoyoさん

どうも「**t0ns0ku426**」です。この度はこちらのIssueでのお返事を有り難うございます。

昨日、Vercel にあります自身の該当のblog内の **Environment Variables** を確認いたしましたところ、

![スクリーンショット (157)](https://user-images.githubusercontent.com/98651974/154804143-e19d66b2-4407-45c8-8abf-52fd4c7e03f4.png)

**NAME**に`NOTION_API_SECRET`・**VALUE**に`DATABASE_ID`と、ひとつに入れてしまっていた事で

`NOTION_API_SECRET is missing from env`というエラーログが出てしまう状態になっておりました。

なので、以下のように

![スクリーンショット (156)](https://user-images.githubusercontent.com/98651974/154804523-7bb177f1-5f3f-4466-8a14-5e3750b2be0b.png)

`DATABASE_ID`と`NOTION_API_SECRET`の **Environment Variables** を

それぞれ別に作成することで、無事にこの問題は解決いたしました。

しかし、また別の問題が発生いたしまして、

(以下スクショ画像掲載)

![スクリーンショット (159)](https://user-images.githubusercontent.com/98651974/154805437-d06e2164-d6b6-4554-9a2b-510dcf523b23.png)

（※同様に`/`・`/blog/before/2021-11-03`・`/blog/tag/Diary`・`/404`・`/500`・`/blog/my-first-post`が

上記スクショ画像にあります [**Error occurred prerendering page**](https://nextjs.org/docs/messages/prerender-error) のエラーが発生いたしました。）

![スクリーンショット (167)](https://user-images.githubusercontent.com/98651974/154805899-3d1dcbae-a760-4c3b-b083-93329a64a08d.png)

最終的な`Error: Command "yarn run build" exited with 1`という表示は変わらなかったのですが、

それ以外での自身の対応としてはどのように作業をしたら宜しいでしょうか。

是非ともアドバイスの方、宜しくお願いいたします。

**Comment by otoyo** [comment]
https://github.com/otoyo/easy-notion-blog/issues/42 で報告された不具合の可能性があります。
リポジトリを最新の状態に更新していただくと修正が入るため、その後再度お試しいただけますでしょうか。

**Comment by t0ns0ku426** [comment]
早急のお返事をありがとうございます。

先程、改めてVercelでデプロイしてみたところ

![スクリーンショット (169)](https://user-images.githubusercontent.com/98651974/154843602-0830bacf-5647-4427-b878-afe3c35e307f.png)

無事にエラーログも出ないままデプロイが完了し、自身の`Notion Blog`をちゃんと表示することが出来ましたー。

この件についての問題解決までのアドバイスを、本当にありがとうございました。

**Comment by herohoro** [comment]
無事解決おめでとうございます＼(^o^)／＼(^o^)／
t0ns0ku426さんとアルパカ先生のやりとりがすごく勉強になるのでとっても有意義なIssueだなと思いました。
ありがとうございます⭐(*´ω｀*)

**Comment by otoyo** [comment]
解決して良かったです。ブログ楽しんでください。
