### ISSUE TITLE
相談：image/next により生じる画像高さの余白

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#49]
## 困っていること
記事内(image block)にその都度サイズが異なり予めサイズを統一できない画像(スクショ)を埋め込むと横長・縦長の画像に異様な余白が生じてしまいます。

## やったこと
- [x] 高さの値を修正し、横長・縦長画像の表示のされ方を見ながら丁度いい値は無いか調べました。
👉 「どっちを取るか」の判断となり縦長画像を見やすく高さを設定すれば横長画像は上下余白が大きくなり画像として見にくくなってしまっています。。。。
<img width="827" alt="スクリーンショット 2022-02-23 12 39 09" src="https://user-images.githubusercontent.com/24947347/155258031-6f03affc-87b9-407e-834d-5ce9ad009e57.png">
詳細：herohoro/easy-notion-blog-02/issues/5

- [x] 直接importすれば画像サイズを指定しなくていい・・といった[記事](https://qiita.com/dtakkiy/items/d153cf44de7a6dae9a8f)を見つけ検討してみました。
👉 publicフォルダに収納する画像ではないので意味が違うなと思い八方塞がりになりました。

## まとめ
予め画像のサイズを指定するのは難しい場合に読者の見やすい画像設定をする方法はありませんか？？？

**Comment by otoyo** [comment]
画像の領域を指定しても縦長、横長の両方に対応することはできず、余白ができてしまったり変に拡大されてしまうのは自分も何とかしたいと思っていたところなので、サイズを取得する方向で解決策を考えてみます。

**Comment by herohoro** [comment]
ありがとうございます😭

**Comment by otoyo** [comment]
https://github.com/otoyo/easy-notion-blog/pull/50 で画像本来のサイズで表示するようにしました。
スクリーンショットや小さめの画像では余白が無くなって違和感なく表示できる反面、写真のようにもともと大きい画像はかなり大きく表示されてしまいます。しかしこれは `img` タグでもそうなのでご了承いただければと思います。

**Comment by herohoro** [comment]
さっそく同期させていただきましたm(_ _)m
確認すると・・・
▼ 　横長
<img width="828" alt="スクリーンショット 2022-02-23 20 57 42" src="https://user-images.githubusercontent.com/24947347/155315252-07eadf9c-fc88-4b33-94ec-d903525b642a.png">
  
▼　縦長
<img width="810" alt="スクリーンショット 2022-02-23 20 57 57" src="https://user-images.githubusercontent.com/24947347/155315339-2e08d833-9dcb-472a-b6ce-612137149dc3.png">
  
すごいです＼(^o^)／
そして早い！！！
これでサムネ部分もimage/nextの方で修正できそうです！！！！
ありがとうございます(*´ω`*)⭐

**Comment by otoyo** [comment]
確認ありがとうございました。
