### ISSUE TITLE
調査報告：notion上のテキスト・ブロック装飾反映の可否

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#5]
【文字装飾】

  | 反映確認
-- | --
テキスト | ⭕
段落テキスト |  
ブロック内改行 |  
空ブロック | ⭕
・リスト | ⭕
・子リスト |  
To-doリスト |  
Numリスト | ⭕
Num子リスト |  
color-block |  
color-text |  
h2タイトル | ⭕
絵文字 | ⭕
画像 | ⭕
太字 | ⭕
下線文字 | ⭕
取り消し線文字 | ⭕
コード文字 | ⭕
inline-page |  
table|  
toggleリスト |  
子toggleリスト |  
Quote | ⭕
callout | ⭕
inline-database |  
codeblock | ⭕
Web bookmark |  
Video |  
embed |  
mention-page |  
sync |  
twitter embed |  

notion上でよく使われる装飾

- color block
- color text
- table
- Web bookmark
  
あったら嬉しい装飾
- twitter  embed

**Comment by otoyo** [comment]
調べてくださりありがとうございます。
Notion APIがサポートしていたら対応したいと思います。

**Comment by otoyo** [comment]
Twitter embed は https://github.com/otoyo/easy-notion-blog/pull/7 で対応しました。

**Comment by otoyo** [comment]
https://github.com/otoyo/easy-notion-blog/pull/12 https://github.com/otoyo/easy-notion-blog/pull/13 で Web bookmark に対応しました。

**Comment by otoyo** [comment]
Color Text, Color Background, Table は現時点では Notion API がサポートしていなかったので、サポートしたら対応したいと思います。
https://developers.notion.com/reference/block#block-object-keys

**Comment by herohoro** [comment]
- Color Text
- Color Background
👆
このサポートが追加されると一気に「easy」レベルが増しそうですね。

私のようなカスタマイズが不要になります＼(^o^)／
<img width="654" alt="スクリーンショット 2021-12-20 0 01 30" src="https://user-images.githubusercontent.com/24947347/146679796-c4976ff7-36d0-4a29-81a8-c40dcf040071.png">
https://easy-notion-blog-02.vercel.app/blog/page-h1_h2-css

**Comment by herohoro** [comment]
12月24日にNotionに追加されたcodeblockの【Mermaid】モード。
▼　Notion上
<img width="767" alt="スクリーンショット 2021-12-25 11 18 16" src="https://user-images.githubusercontent.com/24947347/147376023-9a2a96ec-2448-41a7-8147-0892eb1f2220.png">

ブログではプレビューの反映無しの状況です。
▼　ブログ上
<img width="637" alt="スクリーンショット 2021-12-25 11 20 43" src="https://user-images.githubusercontent.com/24947347/147376041-82033028-72ee-4a0e-9232-3ec15e54da91.png">
https://easy-notion-blog-02.vercel.app/blog/support_check

以上ご報告でしたm(_ _)m

**Comment by otoyo** [comment]
Notion API が対応しているブロック種類はこちらで確認できます。
https://developers.notion.com/reference/block

Notion に実装された機能が API に実装されるのは、実装されるとしてもかなり先になりそうです。

**Comment by otoyo** [comment]
https://github.com/otoyo/easy-notion-blog/pull/40 こちらで mermaid をサポートしましたのでこちらの Issue はクローズします。

**Comment by herohoro** [comment]
ありがとうございます〜〜〜〜〜m(_ _)m
こんなに早くサポートされるとは思いませんでした。。。
