### ISSUE TITLE
不具合：記事を更新したら'FUNCTION_INVOCATION_TIMEOUT'になってしまう

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#53]
## 現状報告

- 過去の記事ページへは問題なく開ける
- 過去の記事でもサムネはいくらリロードしても表示されない

## ▼ エラー画面

<img width="587" alt="スクリーンショット 2022-02-26 10 57 04" src="https://user-images.githubusercontent.com/24947347/155824530-d96994e8-27d1-4faa-af69-699b082c00ef.png">

## Vercel Function

<img width="1051" alt="スクリーンショット 2022-02-26 10 58 40" src="https://user-images.githubusercontent.com/24947347/155824580-5b72d1b3-9cf1-4990-b038-95f3d25c9f26.png">

**Comment by herohoro** [comment]
#52 で対応していただき同期

## Vercel エラー
<img width="1052" alt="スクリーンショット 2022-02-26 11 00 39" src="https://user-images.githubusercontent.com/24947347/155824649-8525de9d-5b57-49d6-a335-ffb3c35a4ff9.png">

👆 上記のようなエラーメッセージが２件発生。

## 開発環境で確認

<img width="1071" alt="スクリーンショット 2022-02-26 11 03 08" src="https://user-images.githubusercontent.com/24947347/155824733-b67d0173-c2b6-4735-978c-304e9e4fc818.png">

私の方で過去に手を加えた部分が影響していないかを確認してみましたが、お手上げ状態ですm(_ _)m

**Comment by herohoro** [comment]
## 報告
無事通りました！！！！！

原因は私の方でテスト用として投稿した記事に未記入列が含まれていたのが影響していたっぽいです。
その記事を削除後再度deployを実行したらエラーがクリアになりました。


お騒がせしましたm(_ _)m

**Comment by otoyo** [comment]
解決してよかったです 👍
