### ISSUE TITLE
ビルドでエラーが出てしまいデプロイできずご教授いただけますと幸いです…！

### ISSUE THREAD

**Issue by sugawaraplus** [otoyo/easy-notion-blog#62]
下記の手順に従いVercelでデプロイしようとしたんですがエラーになってしまいました
https://github.com/otoyo/easy-notion-blog/blob/main/README.ja.md#%E3%82%AF%E3%82%A4%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88

ビルド内容は下記のとおりです
10:31:52.794 | Cloning github.com/sugawaraplus/easy-notion-blog (Branch: main, Commit: e370b16)
-- | --
10:31:53.470 | Cloning completed: 675.105ms
10:31:53.508 | Analyzing source code...
10:31:53.709 | Installing build runtime...
10:31:56.532 | Build runtime installed: 2.822s
10:31:56.990 | Looking up build cache...
10:31:57.125 | Build Cache not found
10:31:57.407 | Installing dependencies...
10:31:57.745 | yarn install v1.22.17
10:31:57.842 | [1/4] Resolving packages...
10:31:58.344 | [2/4] Fetching packages...
10:32:31.623 | [3/4] Linking dependencies...
10:32:31.627 | warning " > @zeit/react-jsx-parser@2.0.0" has incorrect peer dependency "react@^16.8.3".
10:32:31.627 | warning " > @zeit/react-jsx-parser@2.0.0" has incorrect peer dependency "react-dom@^16.8.3".
10:32:31.628 | warning " > react-twitter-embed@3.0.3" has unmet peer dependency "prop-types@^15.5.4".
10:32:31.629 | warning " > react-twitter-embed@3.0.3" has incorrect peer dependency "react@^15.0.0 \|\| ^16.0.0".
10:32:31.629 | warning " > react-twitter-embed@3.0.3" has incorrect peer dependency "react-dom@^15.0.0 \|\| ^16.0.0".
10:32:31.630 | warning "react-twitter-embed > enzyme-adapter-react-16@1.15.6" has unmet peer dependency "enzyme@^3.0.0".
10:32:31.630 | warning "react-twitter-embed > enzyme-adapter-react-16@1.15.6" has incorrect peer dependency "react@^16.0.0-0".
10:32:31.630 | warning "react-twitter-embed > enzyme-adapter-react-16@1.15.6" has incorrect peer dependency "react-dom@^16.0.0-0".
10:32:31.631 | warning "react-twitter-embed > enzyme-adapter-react-16 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x \|\| 0.14.x \|\| ^15.0.0-0 \|\| ^16.0.0-0".
10:32:31.631 | warning "react-twitter-embed > enzyme-adapter-react-16 > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
10:32:31.632 | warning "react-twitter-embed > enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 \|\| ^15.0.0 \|\| ^16.0.0-alpha".
10:32:31.632 | warning " > @typescript-eslint/eslint-plugin@5.11.0" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
10:32:49.101 | [4/4] Building fresh packages...
10:32:49.715 | Done in 51.98s.
10:32:49.743 | Detected Next.js version: 12.0.10
10:32:49.745 | Running "yarn run build"
10:32:50.115 | yarn run v1.22.17
10:32:50.163 | $ node scripts/set-blog-index-cache.js && next build && node scripts/expire-blog-index-cache.js
10:32:50.480 | Cached 0 posts into /vercel/path0/.blog_index_data
10:32:51.344 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
10:32:51.345 | This information is used to shape Next.js' roadmap and prioritize features.
10:32:51.345 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
10:32:51.346 | https://nextjs.org/telemetry
10:32:51.346 |  
10:32:51.400 | info  - Checking validity of types...
10:32:59.707 | info  - Creating an optimized production build...
10:33:19.377 | info  - Compiled successfully
10:33:19.377 | info  - Collecting page data...
10:33:19.808 | Found cached posts.
10:33:19.813 |  
10:33:19.813 | > Build error occurred
10:33:19.814 | TypeError: Cannot read property 'Date' of undefined
10:33:19.815 | at getStaticPaths (/vercel/path0/.next/server/pages/blog/before/[date].js:65:117)
10:33:19.816 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
10:33:19.816 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:497:31)
10:33:19.816 | at async /vercel/path0/node_modules/next/dist/build/utils.js:640:119
10:33:19.817 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20) {
10:33:19.817 | type: 'TypeError'
10:33:19.860 | error Command failed with exit code 1.
10:33:19.861 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:33:19.875 | Error: Command "yarn run build" exited with 1

他に必要な情報などあれば合わせてご教授願います！
よろしくお願いいたしますー！

**Comment by otoyo** [comment]
原因としては下記の2つが考えられます。

## 1. Notion データベースの列名に `Date` がない

Notion ブログのデータベースの列は [データベースプロパティ](https://github.com/otoyo/easy-notion-blog/blob/main/README.ja.md#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3) に載っているプロパティ名通りである必要があります。
初期化スクリプトを実行すると自動で生成されるはずなので、列名がこの通りになっているかどうか確認いただき、なっていなければ手順10の初期化スクリプトを実行するようお願いします。

## 2. Notion データベースに記事(行)が1つもない

Notion データベースに記事を表す行がないケースが考えられます。
これも初期化スクリプトを実行すると自動で生成されますので、行がない場合は手順10で初期化スクリプトを実行してみてください。

もしそれでも解決しないようであれば、(1)Notion データベースのスクリーンショットと(2)初期化スクリプト実行時のログ(`NOTION_API_SECRET` は伏せてください)を載せてコメントいただければと思います。

**Comment by sugawaraplus** [comment]
ご教授いただいた箇所を確認、修正してデプロイできましたー！！！

`Data`はあったんですがデータベースの`Tags`が`Tag`になっていたので修正したのと、[データベースプロパティ](https://github.com/otoyo/easy-notion-blog/blob/main/README.ja.md#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3)の順にしたらできました！！！！！
ありがとうございますー！！！！！

**Comment by otoyo** [comment]
解決して良かったです 👍
