### ISSUE TITLE
不具合：記事一覧「Next page >」の反応無し

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#8]
次のページの表示がされなくなりました。
今回のバージョンアップを同期後に生じた不具合です。

**Comment by otoyo** [comment]
ご報告ありがとうございます。 https://github.com/otoyo/easy-notion-blog/pull/10 で修正しました。

**Comment by herohoro** [comment]
ありがとうございました＼(^o^)／
