### ISSUE TITLE
tag一覧ページの遷移でfirstPostのエラーにより遷移できず

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#82]
唯一「easy-notion-blog_最新情報」というタグが10件以上あるので確認してみると、
ページへ移動するボタンの表示がされない状態でした。

開発画面上では問題ないです。
vercelでは怒られてしまいます....。

以下のようなエラーメッセージがタグ毎に表示される状態です。
<img width="1059" alt="スクリーンショット 2022-05-17 17 50 10" src="https://user-images.githubusercontent.com/24947347/168771532-03370bf1-80bb-4dc0-aed7-234f349adec4.png">

もしかすると取り込み漏れもあるかもしれません。(改造してますし...)

何か手がかりがありましたら教えていただけるとありがたいです。(´ﾟдﾟ｀)

**Comment by otoyo** [comment]
エラーが発生しているブランチを教えていただけますか？
見てみますね。

**Comment by herohoro** [comment]
#79 
<img width="673" alt="スクリーンショット 2022-05-17 18 48 19" src="https://user-images.githubusercontent.com/24947347/168783017-430f2554-d2af-453c-84a5-f0c119e13909.png">
ブランチ....
このmargeのコードです。
(この回答でよかったですか？？)

**Comment by otoyo** [comment]
main ブランチで起きているということですね。承知しました。

**Comment by otoyo** [comment]
リポジトリを見た感じ main でなくて master でしたね。

**Comment by otoyo** [comment]
easy-notion-blog の不具合だったので https://github.com/otoyo/easy-notion-blog/pull/83 の差分を取り込んでみてください。

**Comment by herohoro** [comment]
私のリポジトリのブランチのことでしたか....
勘違いしておりました(；・∀・)


無事Vercel通過しました！！！！
<img width="933" alt="スクリーンショット 2022-05-17 20 41 49" src="https://user-images.githubusercontent.com/24947347/168802967-73161f60-ad64-4eb3-8b97-018d6ec241f2.png">


お手上げ状態だったので助かりました！！！
ありがとうございますm(_ _)mm(_ _)mm(_ _)m

**Comment by otoyo** [comment]
解決して良かったです。
