### ISSUE TITLE
React v16 に依存しているライブラリがあり `npm install` に失敗する

### ISSUE THREAD

**Issue by hideyukisaito** [otoyo/easy-notion-blog#85]
はじめまして、自分のブログに導入してみようと思い検証しています。

## 問題の詳細

プロジェクト自体は React v17 を使用しているが、 `@zeit/react-jsx-parser@2.0.0` と `react-twitter-embed@3.0.3` が React v16 に依存しており `npm install` に失敗する。

---

プロジェクト内を検索したところ `@zeit/react-jsx-parser` については使用箇所が見当たらなかったのですがどこで使用されていますか？最終アップデートも3年前とかなり古いライブラリですので、代替となるライブラリとの入れ替えを検討した方がいいかと思いました。

また `react-twitter-embed` については最新のバージョンが 4.0.4 となっていますのでアップデートをした方がいいのではないかと思います。

**Comment by otoyo** [comment]
初めまして、easy-notion-blog の導入を検討くださりありがとうございます。

ご指摘いただいた `@zeit/react-jsx-parser@2.0.0` は現在は使用していないため削除し、 `react-twitter-embed@3.0.3` については 4.0.4 にアップデートしました。
他、React 16 に依存しているライブラリも可能な限りアップデートを行いました。すでに main ブランチに反映済みです。
差分は https://github.com/otoyo/easy-notion-blog/pull/86 をご確認ください。

他にも何か不明点、ご指摘などありましたらお気軽にご連絡ください。引き続きよろしくお願いいたします。

**Comment by hideyukisaito** [comment]
早速のご対応ありがとうございます！修正が確認できましたので close いたします。
