### ISSUE TITLE
不具合：記事末尾のSNSボタンが消滅している

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#9]
差分を同期後の異変です。

**Comment by otoyo** [comment]
easy-notion-blog のデモページではソーシャルボタンは問題なく表示されているようです。
https://easy-notion-blog-otoyo.vercel.app/blog/my-2nd-post

また https://github.com/herohoro/easy-notion-blog-02 のリポジトリをローカルで動かしてみてもソーシャルボタンは表示されていました。

![スクリーンショット 2021-12-18 13 57 04](https://user-images.githubusercontent.com/1063435/146629614-15c6be17-4abc-4287-91aa-c24a5f0b1902.png)

Vercel の Settings > Environment Variables に `NEXT_PUBLIC_URL` が設定されていますでしょうか？
https://easy-notion-blog-02.vercel.app/blog/v0111_sns_setting
ちょうどこちらのブログで設定されていると思いますが、念の為ご確認をお願いいたします。

**Comment by herohoro** [comment]
ありがとうございます。こちらの不注意でした。
Homeリンクをコピーして貼り付けた際
「末尾の半角スラッシュ」を削除して再度設定すると反映されました。(｡>﹏<｡)

https://easy-notion-blog-02.vercel.app/blog/v0111_sns_setting
こちらの記事にも追記させていただきます。

**Comment by otoyo** [comment]
自分の方で末尾に半角スラッシュを付けたところ、再現しなかったので原因は謎ですね。
ともあれ直ったようで良かったです。
