### ISSUE TITLE
同じリポジトリ使用中の記事をbookmarkするとogImageが発行されない

### ISSUE THREAD

**Issue by herohoro** [otoyo/easy-notion-blog#99]
easy-notion-blogを使う人同士で記事をbookmarkした際、画像を取り込めていない事に気づきました。

https://github.com/otoyo/easy-notion-blog/issues/91
再びの投稿失礼しますm(_ _)m

🔽notion
<img width="806" alt="スクリーンショット 2022-07-14 12 22 33" src="https://user-images.githubusercontent.com/24947347/178891607-648dd56e-7cf3-439b-8fc4-af3afffe7026.png">

🔽ブログで表示
<img width="708" alt="スクリーンショット 2022-07-14 12 22 54" src="https://user-images.githubusercontent.com/24947347/178891615-b6cffba6-4ba4-4078-9976-29d2dbc7d4f3.png">

🔽Twitterで確認_validator
<img width="1039" alt="スクリーンショット 2022-07-14 12 25 29" src="https://user-images.githubusercontent.com/24947347/178891624-a6d38520-703b-4f06-892d-96b9acc3cebe.png">

🔽Twitterで打ってみる
<img width="484" alt="スクリーンショット 2022-07-14 12 31 39" src="https://user-images.githubusercontent.com/24947347/178892143-8747cfdf-939d-4d45-9483-5d134c5b16e4.png">

🔽demoサイト以外の記事で試す_validator
<img width="995" alt="スクリーンショット 2022-07-14 12 32 40" src="https://user-images.githubusercontent.com/24947347/178892268-173b1b74-f189-42de-8af9-eb846d400ee9.png">
<img width="1017" alt="スクリーンショット 2022-07-14 12 33 29" src="https://user-images.githubusercontent.com/24947347/178892334-3e344732-1eac-4813-8010-6da74539ca14.png">

🔽Twitterで打ってみる
<img width="498" alt="スクリーンショット 2022-07-14 12 35 04" src="https://user-images.githubusercontent.com/24947347/178892519-c7bee420-8744-425f-b1f7-30538c92de04.png">
<img width="500" alt="スクリーンショット 2022-07-14 12 34 51" src="https://user-images.githubusercontent.com/24947347/178892511-45f92f2c-fa2e-4b71-bde5-1b76a2c6ea7e.png">

**********
記事に埋め込んだbookmarkの画像が発行されない問題...

なかなか難しいことだと思いますのでお時間あるときにでも何か術があれば...と願っておりますm(_ _)m

**Comment by otoyo** [comment]
再現することを確認しました。
Twitter Card Validator でも再現するので Bookmark コンポーネントの問題ではなさそうです。
Twitter Card Validator に https://github.com/ を入力しても同じように Unable to render Card preview となるので、おそらく easy-notion-blog の問題ではなさそうな気がします。

easy-notion-blog の Bookmark コンポーネントについては https://github.com/otoyo/easy-notion-blog/issues/107 で修正したのでご確認いただけますと幸いです。

**Comment by herohoro** [comment]
bookmarkのスクラッチ開発後に確認させていただくと...
表示されていました！！！！
<img width="779" alt="スクリーンショット 2022-08-20 4 53 58" src="https://user-images.githubusercontent.com/24947347/185697392-8514d845-0fae-472f-9f6d-70331b00c291.png">

そしてOgImage列の画像をサムネにして記事一覧に表示している画像も
いままで空commitをしないとなかなか表示されずしびれを切らして(多分待てば表示されたのかもしれませんが)空commitをして表示させていたところも今回のbookmarkブロックの改良ですぐに表示されることも確認できました！！

ありがとうございます！
全てが良くなりました！！！！

**Comment by otoyo** [comment]
解決してよかったです。ご確認ありがとうございました。
